---
# tasks file for nginx

  - name: Make sure apache is running
    become: yes
    action: service name=apache2 state=stopped enabled=true

  - name: Install Nginx packages
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    with_items: "{{ nginx_packages }}"
    notify: restart-apache

  - name: Make sure Nginx is running
    become: yes
    action: service name=nginx state=started enabled=true

  - name: Generate dhparam
    become: yes
    shell: openssl dhparam 2048 -out /etc/ssl/private/dhparam.pem

  - name: Place `/etc/nginx/nginx.conf`
    become: yes
    template:
      force: yes
      src: nginx.conf.j2
      dest: "/etc/nginx/nginx.conf"
    notify: restart-nginx

  # - name: Place `/etc/nginx/conf.d/default.conf`
  #   become: yes
  #   template:
  #     force: yes
  #     src: default.conf.j2
  #     dest: "/etc/nginx/conf.d/default.conf"
  #   notify: restart-nginx

  - name: Change owner `/var/cache/nginx`
    become: yes
    file:
      path: /var/cache/nginx
      state: directory
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      mode: 0755

  - name: Place the `index.html`
    become: yes
    copy:
      src: index.html
      dest: "/var/www/html/index.html"
      mode: "0644"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      force: false

  - name: Create directory `/etc/nginx/ssl`
    become: yes
    file:
      path: /etc/nginx/ssl
      state: directory
      mode: 0755

  - name: Create SSL keys
    become: yes
    command: openssl req -batch -new -x509 -newkey rsa:2048 -nodes -sha256 \
      -subj /CN=*/O=Dummy -days 365 \
      -keyout /etc/nginx/ssl/server.key \
      -out /etc/nginx/ssl/server.crt
